project:
  type: website

website:
  title: "Wei Yang Tham"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: files/wytham_cv.pdf
        text: CV
        target: "_blank"
      - publicgoods.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    

editor: visual

